const nacionalidades = {
    "Afganistán": "afgano",
    "Albania": "albanés",
    "Alemania": "alemán",
    "Andorra": "andorrano",
    "Angola": "angolés",
    "Antigua y Barbuda": "antiguano",
    "Arabia Saudita": "saudí",
    "Argelia": "argelino",
    "Argentina": "argentino",
    "Armenia": "armenio",
    "Australia": "australiano",
    "Austria": "austriaco",
    "Azerbaiyán": "azerí",
    "Bahamas": "bahameño",
    "Bangladés": "bangladesí",
    "Barbados": "barbadense",
    "Baréin": "bareiní",
    "Bélgica": "belga",
    "Belice": "beliceño",
    "Benín": "beninés",
    "Bielorrusia": "bielorruso",
    "Birmania": "birmano",
    "Bolivia": "boliviano",
    "Bosnia y Herzegovina": "bosnio",
    "Botsuana": "botsuano",
    "Brasil": "brasileño",
    "Brunéi": "bruneano",
    "Bulgaria": "búlgaro",
    "Burkina Faso": "burkinés",
    "Burundi": "burundés",
    "Bután": "butanés",
    "Cabo Verde": "caboverdiano",
    "Camboya": "camboyano",
    "Camerún": "camerunés",
    "Canadá": "canadiense",
    "Catar": "catarí",
    "Chad": "chadiano",
    "Chile": "chileno",
    "China": "chino",
    "Chipre": "chipriota",
    "Colombia": "colombiano",
    "Comoras": "comorense",
    "Corea del Norte": "norcoreano",
    "Corea del Sur": "surcoreano",
    "Costa de Marfil": "marfileño",
    "Costa Rica": "costarricense",
    "Croacia": "croata",
    "Cuba": "cubano",
    "Dinamarca": "danés",
    "Dominica": "dominiqués",
    "Ecuador": "ecuatoriano",
    "Egipto": "egipcio",
    "El Salvador": "salvadoreño",
    "Emiratos Árabes Unidos": "emiratí",
    "Eritrea": "eritreo",
    "Eslovaquia": "eslovaco",
    "Eslovenia": "esloveno",
    "España": "español",
    "Estados Unidos": "estadounidense",
    "Estonia": "estonio",
    "Esuatini": "suazi",
    "Etiopía": "etíope",
    "Filipinas": "filipino",
    "Finlandia": "finlandés",
    "Fiyi": "fiyiano",
    "Francia": "francés",
    "Gabón": "gabonés",
    "Gambia": "gambiano",
    "Georgia": "georgiano",
    "Ghana": "ghanés",
    "Granada": "granadino",
    "Grecia": "griego",
    "Guatemala": "guatemalteco",
    "Guinea": "guineano",
    "Guinea Ecuatorial": "ecuatoguineano",
    "Guinea-Bisáu": "guineano",
    "Guyana": "guyanés",
    "Haití": "haitiano",
    "Honduras": "hondureño",
    "Hungría": "húngaro",
    "India": "indio",
    "Indonesia": "indonesio",
    "Irak": "iraquí",
    "Irán": "iraní",
    "Irlanda": "irlandés",
    "Islandia": "islandés",
    "Islas Marshall": "marshalés",
    "Islas Salomón": "salomonense",
    "Israel": "israelí",
    "Italia": "italiano",
    "Jamaica": "jamaiquino",
    "Japón": "japonés",
    "Jordania": "jordano",
    "Kazajistán": "kazajo",
    "Kenia": "keniano",
    "Kirguistán": "kirguís",
    "Kiribati": "kiribatiano",
    "Kuwait": "kuwaití",
    "Laos": "laosiano",
    "Lesoto": "lesotense",
    "Letonia": "letón",
    "Líbano": "libanés",
    "Liberia": "liberiano",
    "Libia": "libio",
    "Liechtenstein": "liechtensteiniano",
    "Lituania": "lituano",
    "Luxemburgo": "luxemburgués",
    "Macedonia del Norte": "macedonio",
    "Madagascar": "malgache",
    "Malasia": "malasio",
    "Malaui": "malauí",
    "Maldivas": "maldivo",
    "Malí": "maliense",
    "Malta": "maltés",
    "Marruecos": "marroquí",
    "Mauricio": "mauriciano",
    "Mauritania": "mauritano",
    "México": "mexicano",
    "Micronesia": "micronesio",
    "Moldavia": "moldavo",
    "Mónaco": "monegasco",
    "Mongolia": "mongol",
    "Montenegro": "montenegrino",
    "Mozambique": "mozambiqueño",
    "Namibia": "namibio",
    "Nauru": "nauruano",
    "Nepal": "nepalí",
    "Nicaragua": "nicaragüense",
    "Níger": "nigerino",
    "Nigeria": "nigeriano",
    "Noruega": "noruego",
    "Nueva Zelanda": "neozelandés",
    "Omán": "omaní",
    "Países Bajos": "neerlandés",
    "Pakistán": "pakistaní",
    "Palaos": "palauano",
    "Panamá": "panameño",
    "Papúa Nueva Guinea": "papú",
    "Paraguay": "paraguayo",
    "Perú": "peruano",
    "Polonia": "polaco",
    "Portugal": "portugués",
    "Reino Unido": "británico",
    "República Centroafricana": "centroafricano",
    "República Checa": "checo",
    "República Democrática del Congo": "congoleño",
    "República Dominicana": "dominicano",
    "Ruanda": "ruandés",
    "Rumania": "rumano",
    "Rusia": "ruso",
    "Samoa": "samoano",
    "San Cristóbal y Nieves": "cristobaleño",
    "San Marino": "sanmarinense",
    "San Vicente y las Granadinas": "vicentino",
    "Santa Lucía": "santaluciense",
    "Santo Tomé y Príncipe": "santomense",
    "Senegal": "senegalés",
    "Serbia": "serbio",
    "Seychelles": "seychellense",
    "Sierra Leona": "sierraleonés",
    "Singapur": "singapurense",
    "Siria": "sirio",
    "Somalia": "somalí",
    "Sri Lanka": "ceilandés",
    "Sudáfrica": "sudafricano",
    "Sudán": "sudanés",
    "Sudán del Sur": "sursudanés",
    "Suecia": "sueco",
    "Suiza": "suizo",
    "Surinam": "surinamés",
    "Tailandia": "tailandés",
    "Taiwán": "taiwanés",
    "Tanzania": "tanzano",
    "Tayikistán": "tayiko",
    "Timor Oriental": "timorense",
    "Togo": "togolés",
    "Tonga": "tongano",
    "Trinidad y Tobago": "trinitense",
    "Túnez": "tunecino",
    "Turkmenistán": "turcomano",
    "Turquía": "turco",
    "Tuvalu": "tuvaluano",
    "Ucrania": "ucraniano",
    "Uganda": "ugandés",
    "Uruguay": "uruguayo",
    "Uzbekistán": "uzbeko",
    "Vanuatu": "vanuatuense",
    "Vaticano": "vaticano",
    "Venezuela": "venezolano",
    "Vietnam": "vietnamita",
    "Yemen": "yemení",
    "Yibuti": "yibutiano",
    "Zambia": "zambiano",
    "Zimbabue": "zimbabuense"
};

// Función para capitalizar la primera letra de una palabra
function capitalizarPrimeraLetra(palabra) {
    return palabra.charAt(0).toUpperCase() + palabra.slice(1);
}

// Función para llenar un <select> con las nacionalidades
function llenarNacionalidades(selectId) {
    const select = document.getElementById(selectId);
    if (!select) return;

    // Limpiar el <select>
    select.innerHTML = '';

    // Agregar opción por defecto
    const defaultOption = document.createElement('option');
    defaultOption.value = '';
    defaultOption.textContent = '--Seleccionar Nacionalidad--';
    select.appendChild(defaultOption);

    // Agregar opción para la nacionalidad peruana seleccionada por defecto
    const peruvianOption = document.createElement('option');
    peruvianOption.value = 'peruano';
    peruvianOption.textContent = 'Peruano';
    peruvianOption.selected = true;
    select.appendChild(peruvianOption);

    // Llenar el <select> con las demás nacionalidades capitalizadas
    for (const nacionalidad of Object.values(nacionalidades)) {
        if (nacionalidad !== 'peruano') {
            const option = document.createElement('option');
            option.value = nacionalidad;
            option.textContent = capitalizarPrimeraLetra(nacionalidad); // Capitalizar la nacionalidad
            select.appendChild(option);
        }
    }
}

// Llenar el <select> cuando el DOM esté listo
document.addEventListener('DOMContentLoaded', () => {
    llenarNacionalidades('nationality');
});